name: 'Notify team'
description: 'Notify the team of any failed action'
inputs:
  webhook:
    description: 'Webhook to the meet channel'
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo MAAAMA MIIIAA
        echo "webhookUrl: ${{ inputs.webhook }}"
        echo "jobStatus: ${{ job.status }}"
        echo "imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}"
        echo "imageAltText: ${{ github.event.head_commit.author.name }}"
        echo "subtitle: ${{ github.event.head_commit.message }}"
        echo "title: ${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"
    - name: Google Chat Notificationa
      uses: SimonScholz/google-chat-action@main
      if: failure()
      # this allows the build to succeed even when the notification fails
      # e.g. due to dependabot push, which may not have the secret
      continue-on-error: true
      with:
        # https://docs.github.com/en/webhooks/webhook-events-and-payloads
        webhookUrl: ${{ inputs.webhook }}
        jobStatus: ${{ job.status }}
        imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}
        imageAltText: ${{ github.event.head_commit.author.name }}
        subtitle: ${{ github.event.head_commit.message }}
        title: "${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"


